# mkdocs serve

site_name: MAS Devops Collection
site_url: https://ibm-mas.github.io/ansible-devops

repo_name: GitHub
repo_url: https://github.com/ibm-mas/ansible-devops
edit_uri: blob/master/docs/

nav:
  - 'Home': index.md
  - 'Changes': changes.md
  - 'Playbooks':
    - 'OCP': playbooks/ocp.md
    - 'Install Core': playbooks/oneclick-core.md
    - 'Add IoT': playbooks/oneclick-iot.md
    - 'Add Manage': playbooks/oneclick-manage.md
    - 'Add Monitor': playbooks/oneclick-monitor.md
    - 'Add Optimizer': playbooks/oneclick-optimizer.md
    - 'Update': playbooks/oneclick-update.md
    - 'Upgrade': playbooks/oneclick-upgrade.md
    - 'Add Visual Inspection': playbooks/oneclick-visualinspection.md
  - 'Roles: OCP Mgmt':
    - 'ocp_deprovision': roles/ocp_deprovision.md
    - 'ocp_disable_updates': roles/ocp_disable_updates.md
    - 'ocp_github_oauth': roles/ocp_github_oauth.md
    - 'ocp_login': roles/ocp_login.md
    - 'ocp_provision': roles/ocp_provision.md
    - 'ocp_roks_upgrade_registry_storage': roles/ocp_roks_upgrade_registry_storage.md
    - 'ocp_upgrade': roles/ocp_upgrade.md
    - 'ocp_verify': roles/ocp_verify.md
  - 'Roles: Dependency Mgmt':
    - 'appconnect': roles/appconnect.md
    - 'cert_manager': roles/cert_manager.md
    - 'cert_manager_upgrade': roles/cert_manager_upgrade.md
    - 'cert_manager_upgrade_check': roles/cert_manager_upgrade_check.md
    - 'cluster_monitoring': roles/cluster_monitoring.md
    - 'cos': roles/cos.md
    - 'cp4d_hack_worker_nodes': roles/cp4d_hack_worker_nodes.md
    - 'cp4d': roles/cp4d.md
    - 'cp4d_service': roles/cp4d_service.md
    - 'cp4d_upgrade': roles/cp4d_upgrade.md
    - 'db2': roles/db2.md
    - 'db2_backup': roles/db2_backup.md
    - 'db2_restore': roles/db2_restore.md
    - 'kafka': roles/kafka.md
    - 'nvidia_gpu': roles/nvidia_gpu.md
    - 'mongodb': roles/mongodb.md
    - 'ocs': roles/ocs.md
    - 'sbo': roles/sbo.md
    - 'sbo_upgrade': roles/sbo_upgrade.md
    - 'sls': roles/sls.md
    - 'uds': roles/uds.md
  - 'Roles: Suite Mgmt':
    - 'suite_app_config': roles/suite_app_config.md
    - 'suite_app_install': roles/suite_app_install.md
    - 'suite_app_upgrade': roles/suite_app_upgrade.md
    - 'suite_config': roles/suite_config.md
    - 'suite_db2_setup_for_manage': roles/suite_db2_setup_for_manage.md
    - 'suite_dns': roles/suite_dns.md
    - 'suite_install': roles/suite_install.md
    - 'suite_manage_attachments_config': roles/suite_manage_attachments_config.md
    - 'suite_mustgather': roles/suite_mustgather.md
    - 'suite_mustgather_download': roles/suite_mustgather_download.md
    - 'suite_upgrade': roles/suite_upgrade.md
    - 'suite_verify': roles/suite_verify.md
  - 'Roles: Utilities':
    - 'ansible_version_check': roles/ansible_version_check.md
    - 'gencfg_jdbc': roles/gencfg_jdbc.md
    - 'gencfg_workspace': roles/gencfg_workspace.md
    - 'install_operator': roles/install_operator.md
    - 'gencfg_watsonstudio': roles/gencfg_watsonstudio.md

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
  prev_next_buttons_location: none
extra_css:
  - extra.css
markdown_extensions:
  - toc:
      permalink: 
  - admonition
  # Add this to support expandable sections
  #- pymdownx.details

# https://squidfunk.github.io/mkdocs-material/extensions/admonition/
# Note
# Abstract
# Info
# Tip
# Success
# Question
# Warning
# Failure
# Danger
# Bug
# Example
# Quote
