---
#ws configuration
cpd_admin_password: "{{ lookup('env', 'CPD_ADMIN_PASSWORD') }}"
cpd_admin_username: "{{ lookup('env', 'CPD_ADMIN_USERNAME') }}"
cpd_url: "{{ lookup('env', 'CPD_URL') }}"
# MAS instance configuration
mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"
mas_workspace_id: "{{ lookup('env', 'MAS_WORKSPACE_ID') }}"
mas_config_scope: "{{ lookup('env', 'MAS_CONFIG_SCOPE') | default('system', true) }}" # Supported values are "system", "ws", "app", or "wsapp"
mas_config_dir: "{{ lookup('env', 'MAS_CONFIG_DIR') }}"
mas_application_id: "{{ lookup('env', 'MAS_APP_ID') }}"
