---
# The following MAS information is needed to lookup the right Manage app instance
# ---------------------------------------------------------------------------------------------------------------------
mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"
mas_workspace_id: "{{ lookup('env', 'MAS_WORKSPACE_ID') }}"

# Manage attachments provider
# ---------------------------------------------------------------------------------------------------------------------
mas_manage_attachments_provider: "{{ lookup('env', 'MAS_MANAGE_ATTACHMENTS_PROVIDER') | default('filestorage', true) }}" # supported options: filestorage or cos

# IBM Cloud Object Storage (ibm)
# ---------------------------------------------------------------------------------------------------------------------
ibmcloud_apikey: "{{ lookup('env', 'IBMCLOUD_APIKEY') }}"
ibmcloud_resourcegroup: "{{ lookup('env', 'IBMCLOUD_RESOURCEGROUP') | default('Default', true) }}"

ibmcos_instance_name: "{{ lookup('env', 'COS_INSTANCE_NAME') }}"
ibmcos_url: "{{ lookup('env', 'COS_ATTACHMENTS_REGION_LOCATION_URL') | default('https://s3.us.cloud-object-storage.appdomain.cloud', true) }}"
ibmcos_location_info: global
ibmcos_attachments_bucket_storage_class: "{{ lookup('env', 'COS_ATTACHMENTS_BUCKET_STORAGE_CLASS') | default('smart', true) }}" # supported: vault, cold, flex or smart - https://cloud.ibm.com/docs/cloud-object-storage/iam?topic=cloud-object-storage-classes#classes-locationconstraint
ibmcos_attachments_bucket_name: "{{ lookup('env', 'COS_ATTACHMENTS_BUCKET_NAME') | default('maxdoc', true) }}"
ibmcos_attachments_bucket_location: "{{ lookup('env', 'COS_ATTACHMENTS_BUCKET_LOCATION') | default('us', true) }}"

# Manage app DB2 instance where COS configuration will be done
# ---------------------------------------------------------------------------------------------------------------------
db2_namespace: "{{ lookup('env', 'DB2_NAMESPACE') | default('db2u', true) }}"
db2_instance_name: "{{ lookup('env', 'DB2_INSTANCE_NAME') }}" # e.g. db2u-iot or db2u-manage
