---

- hosts: localhost
  vars:
    cluster_type: gcp-ipi
    ipi_platform: gcp

  pre_tasks:
    # For the full set of supported environment variables refer to the playbook documentation
    - name: Check for required environment variables
      assert:
        that:
          - lookup('env', 'CLUSTER_NAME') != ""
          - lookup('env', 'OCP_VERSION') != ""
          - lookup('env', 'IPI_COMPUTE_REPLICAS') != ""
          - lookup('env', 'IPI_CONTROLPLANE_REPLICAS') != ""
          - lookup('env', 'IPI_BASE_DOMAIN') != ""
          - lookup('env', 'IPI_PULL_SECRET_FILE') != ""
          - lookup('env', 'PROJECT_ID') != ""
          - lookup('env', 'GOOGLE_APPLICATION_CREDENTIALS') != "" 
        fail_msg: "One or more required environment variables are not defined"

  roles:
    # 1. Provision ocp on gcp
    - ibm.mas_devops.ocp_provision

    # 2. Login and verify the cluster is ready
    # - ibm.mas_devops.ocp_login
    - ibm.mas_devops.ocp_verify
