---
# Add PRedict 8.6.x application to an existing MAS Core 8.8.x + IoT 8.4.x installation
#
# Dependencies:
# - ansible-playbook ibm.mas_devops.oneclick_core
# - ansible-playbook ibm.mas_devops.oneclick_manage
# - ansible-playbook ibm.mas_devops.oneclick_iot
# - ansible-playbook ibm.mas_devops.oneclick_monitor
#
# Predict will be configured to use the same db2 instance that IoT is using
#
- hosts: localhost
  any_errors_fatal: true

  vars:
    # Application Installation
    mas_app_id: predict
    mas_app_channel: "{{ lookup('env', 'MAS_APP_CHANNEL') | default('8.6.x', true) }}"

    # Application Configuration
    mas_workspace_id: "{{ lookup('env', 'MAS_WORKSPACE_ID') | default('masdev', true) }}"
    # these vars will be set by cp4d playbook, if it did not run (eg install_cp4d_platform=false), it will be set by the environment vars.
    cpd_url: "{{ lookup('env', 'CPD_URL') }}"
    cpd_admin_username: "{{ lookup('env', 'CPD_ADMIN_USERNAME') }}"
    cpd_admin_password: "{{ lookup('env', 'CPD_ADMIN_PASSWORD') }}"
    # Install CP4D
    install_cp4d_platform: "{{ lookup('env', 'CP4D_INSTALL_PLATFORM') | default('True', true) | bool }}"
    install_watson_studio: "{{ lookup('env', 'CP4D_INSTALL_WSL') | default('True', true) | bool }}"
    install_watson_machine_learning: "{{ lookup('env', 'CP4D_INSTALL_WML') | default('True', true) | bool }}"
    install_analytics_engine: "{{ lookup('env', 'CP4D_INSTALL_SPARK') | default('True', true) | bool }}"
    install_watson_openscale: "{{ lookup('env', 'CP4D_INSTALL_OPENSCALE') | default('True', true) | bool }}"
    cpd_product_version: "{{ lookup('env', 'CP4D_PRODUCT_VERSION') | default('4.0.9', true) }}"

  pre_tasks:
    - include_role:
      # Cloud Pak for Data Platform (~1 1/2 hours)
        name: ibm.mas_devops.cp4d
      when: install_cp4d_platform == true
    - include_role:
      # Watson Studio (~3 hours)
        name: ibm.mas_devops.cp4d_service
      when: install_watson_studio == true
      vars:
        cpd_service_name: wsl
    - include_role:
      # Watson Machine Learning (~2 1/2 hours)
        name: ibm.mas_devops.cp4d_service
      when: install_watson_machine_learning == true
      vars:
        cpd_service_name: wml
    - include_role:
      # Analytics Engine Powered by Apache Spark (~30 minutes)
        name: ibm.mas_devops.cp4d_service
      when: install_analytics_engine == true
      vars:
        cpd_service_name: spark
    - include_role:
      # Watson OpenScale (~1 hour)
        name: ibm.mas_devops.cp4d_service
      when: install_watson_openscale == true
      vars:
        cpd_service_name: aiopenscale


    # For the full set of supported environment variables refer to the playbook documentation
    - name: Check for required environment variables
      assert:
        that:
          - lookup('env', 'MAS_INSTANCE_ID') != ""
          - lookup('env', 'MAS_ENTITLEMENT_KEY') != ""
          - cpd_url != ""
          - cpd_admin_username != ""
          - cpd_admin_password != ""
        fail_msg: "One or more required environment variables are not defined"

  roles:
    # Generate Watson Studio CFG File (~5 Minutes)
    - name: ibm.mas_devops.gencfg_watsonstudio
      when: install_watson_studio == false
    # Deploy Predict (~15 Minutes)
    - name: ibm.mas_devops.suite_config
      when: install_watson_studio == false
    - name: ibm.mas_devops.suite_app_install
    # Activate Predict in workspace (~30 Minutes)
    - name: ibm.mas_devops.suite_app_config
