galaxy_info:
  author: André Marcelino (@andrercm)
  description: Configure file storage pvc's as persistent storage for Manage application BIM (Building Information Models).
  company: IBM

  license: EPL-2.0

  min_ansible_version: 2.10

  platforms:
    - name: GenericLinux
      versions:
        - all

  galaxy_tags:
    - ibm
    - mas
    - devops
    - rhocp

dependencies:
  - role: ibm.mas_devops.ansible_version_check
