---
# Default application spec for Predict
mas_app_ws_spec:
  bindings:
    jdbc: system
    watsonstudio: system
  settings:
    wml:
      instance_id: "{{ lookup('env', 'WML_INSTANCE_ID') | default('openshift', true) }}"
      url: >-
        {{ cpd_url }}
      version: "{{ cpd_product_version }}"
