db2_instance_name: "{{ lookup('env', 'DB2_INSTANCE_NAME') }}"
db2_namespace: "{{ lookup('env', 'DB2_NAMESPACE') | default('db2u', true) }}"
db2_username: db2inst1
db2_dbname: "{{ lookup('env', 'DB2_DBNAME') | default('BLUDB', true) }}"
db2_tablespace_data_size: "{{ lookup('env', 'DB2_TABLESPACE_DATA_SIZE') | default('5000 M', true) }}"
db2_tablespace_index_size: "{{ lookup('env', 'DB2_TABLESPACE_INDEX_SIZE') | default('5000 M', true) }}"

# TODO: The default that is built into the manage operator isn't following
# the naming conventions for MAS.  It should have been some combination of
# {{mas_instance_id}} {{mas_app_id}} and {{mas_workspace_id}} so that it's
# friendly to shared database sources in low cost environments, and easily
# templateable in automation such as this :(
db2_schema: "{{ lookup('env', 'MAS_APP_SETTINGS_DB2_SCHEMA') | default('maximo', true)}}"
