---
# Default application specs for Predict
mas_app_spec:
  bindings:
    health: workspace
    jdbc: system
    monitor: workspace
    watsonstudio: system
  components: {}
  displayName: Predict Workspace
