---

# 1. Check for undefined properties that do not have a default
# -----------------------------------------------------------------------------
- name: "Fail if required properties are not provided"
  assert:
    that:
      - mas_instance_id is defined and mas_instance_id != ""
      - mas_app_id is defined and mas_app_id != ""
      - mas_workspace_id is defined and mas_workspace_id != ""
    fail_msg: "Missing one or more required properties"


# 2. Load var files
# -----------------------------------------------------------------------------
- name: Load application-workspace variables
  include_vars: "vars/{{ mas_app_id }}.yml"

- name: Load application variables
  include_vars: "{{ role_path }}/../suite_app_install/vars/{{ mas_app_id }}.yml"


# 3. Run Application Specific Tasks
# -----------------------------------------------------------------------------
- name: Run application specific tasks
  when: mas_app_id is in ['hputilities'] # applications which have something to process before configuration
  include_tasks: "tasks/{{ mas_app_id }}.yml"

# The following will auto determine storage classes to be used as persistent volumes for Manage attachments/BIM configurations (Manage OOTB features)
- name: Determine Storage Class for Manage application
  when:
    - mas_app_id is in ['manage'] # applications which have something to process before configuration
    - mas_app_settings_persistent_volumes_flag == 'true'
  include_tasks: "tasks/determine-storage-classes.yml"

# 4. Load default application workspace spec, if user does not provide one
# -----------------------------------------------------------------------------
- name: Load default application workspace spec
  when: mas_app_ws_spec is not defined or mas_app_ws_spec == ""
  include_vars: "vars/defaultspecs/{{ mas_app_id }}.yml"


# 5. Provide debug information
# -----------------------------------------------------------------------------
- name: "Configure namespace"
  set_fact:
    mas_namespace: "mas-{{ mas_instance_id }}-core"
    mas_app_namespace: "mas-{{ mas_instance_id }}-{{ mas_app_id }}"

- name: "Debug information"
  debug:
    msg:
      - "Instance ID ............... {{ mas_instance_id }}"
      - "Application ID ............ {{ mas_app_id }}"
      - "Workspace ID .............. {{ mas_workspace_id }}"
      - "MAS app namespace ......... {{ mas_app_namespace }}"
      - "Templated workspace CR .... {{ lookup('template', 'templates/workspace.yml.j2') }}"


# 6. Workspace configuration
# -----------------------------------------------------------------------------
- name: Configure application in workspace
  kubernetes.core.k8s:
    state: present
    namespace: "{{ mas_app_namespace }}"
    definition: "{{ lookup('template', 'templates/workspace.yml.j2') }}"


# 7. Check if the application is ready
# -----------------------------------------------------------------------------
# Workspaces can only be configured when an application is in Ready state.
#
# If the application is not in ready state we can fail fast rather than waiting
# for the workspace to be Ready -- because it never will!
- name: "Lookup application information"
  kubernetes.core.k8s_info:
    api_version: "{{ mas_app_api_version }}"
    name: "{{ mas_instance_id }}"
    namespace: "{{ mas_app_namespace }}"
    kind: "{{ mas_app_kind }}"
  register: app_cr_result

- name: "Check that the application is ready to configure a workspace"
  assert:
    that:
      - app_cr_result.resources is defined
      - app_cr_result.resources | length > 0
      - app_cr_result.resources | json_query('[*].status.conditions[?type==`Ready`][].status') | select ('match','True') | list | length == 1
    fail_msg: "Workspace {{ mas_workspace_id }} created but application {{ mas_app_id }} is not ready"


# 8. Wait for application workspace to be ready
# -----------------------------------------------------------------------------
- name: "Wait for application workspace to be ready ({{ mas_app_cfg_delay }}s delay)"
  kubernetes.core.k8s_info:
    api_version: "{{ mas_app_ws_apiversion }}"
    kind: "{{ mas_app_ws_kind }}"
    name: "{{ mas_instance_id }}-{{ mas_workspace_id }}"
    namespace: "{{ mas_app_namespace }}"
    wait: yes
    wait_condition:
      status: "True"
      type: Ready
    wait_sleep: 30
    wait_timeout: 120 # before we give up and fall back into the retry loop
  register: app_ws_cr_result
  retries: "{{ mas_app_cfg_retries }}"
  delay: "{{ mas_app_cfg_delay }}"
  until:
    - app_ws_cr_result.resources is defined
    - app_ws_cr_result.resources | length > 0
    - app_ws_cr_result.resources | json_query('[*].status.conditions[?type==`Ready`][].status') | select ('match','True') | list | length == 1
