---
# We don't actually use this dictionary today, but in a future release we should simply pass in the version
# of HP Utilities and key off this instead.
appconnect_defaults: # Based on HP Utilities version
  8.4.x:
    channel: v5.2
    license: L-APEH-C9NCK6
    dashboard: dashboard-12040r2
    dashboard_version: 12.0.4.0-r2
  8.3.x:
    channel: v4.2
    license: L-KSBM-C87FU2
    dashboard: dashboard-12020r2
    dashboard_version: 12.0.2.0-r2
  8.2.x:
    channel: v3.1
    license: L-KSBM-C37J2R
    dashboard: dashboard-12010r2
    dashboard_version: 12.0.1.0-r2

# Define where AppConnect will be installed, the default values below
appconnect_namespace: "{{ lookup('env', 'APPCONNECT_NAMESPACE') | default('ibm-app-connect', true) }}"
appconnect_channel: "{{ lookup('env', 'APPCONNECT_CHANNEL') | default('v5.2', true) }}"
appconnect_dashboard_name: "{{ lookup('env', 'APPCONNECT_DASHBOARD_NAME') | default('dashboard-12040r2', true) }}"
appconnect_dashboard_version: "{{ lookup('env', 'APPCONNECT_DASHBOARD_VERSION') | default('12.0.4.0-r2', true) }}"
appconnect_license_id: "{{ lookup('env', 'APPCONNECT_LICENSE_ID') | default('L-APEH-C9NCK6', true) }}"
appconnect_storage_class: "{{ lookup('env', 'APPCONNECT_STORAGE_CLASS') }}"

# IBM entitlement key for AppConnect
# Default to re-using the IBM entitlement key if we do not provide a specific one for AppConnect
appconnect_entitlement_username: "{{ lookup('env', 'APPCONNECT_ENTITLEMENT_USERNAME') | default('cp', true) }}"
appconnect_entitlement_key: "{{ lookup('env', 'APPCONNECT_ENTITLEMENT_KEY') | default(lookup('env', 'IBM_ENTITLEMENT_KEY'), true) }}"
appconnect_registry: cp.icr.io

# MAS Configuration
mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"
mas_config_dir: "{{ lookup('env', 'MAS_CONFIG_DIR') }}"
