# Watson Discovery 4.5 defines operand requests for rabbitmq and elastic search
# so these resources are created upfront to enable the subscriptions to start up
#
# Custom Operand Registries: Watson Discovery
# -----------------------------------------------------------------------------
---
apiVersion: operator.ibm.com/v1alpha1
kind: OperandRegistry
metadata:
  name: opencontent-rabbitmq-registry
  namespace: ibm-cpd-operators
spec:
  operators:
    - channel: "{{ cpd_wd_components.rabbitmq.channel_name }}"
      installPlanApproval: Automatic
      name: rabbitmq-operator
      namespace: "{{ cpd_operators_namespace }}"
      packageName: ibm-rabbitmq-operator
      scope: public
      sourceNamespace: openshift-marketplace
---
apiVersion: operator.ibm.com/v1alpha1
kind: OperandRegistry
metadata:
  name: opencontent-elasticsearch-registry
  namespace: ibm-cpd-operators
spec:
  operators:
    - channel: "{{ cpd_wd_components.elasticsearch.channel_name }}"
      installPlanApproval: Automatic
      name: elasticsearch-operator
      namespace: "{{ cpd_operators_namespace }}"
      packageName: ibm-elasticsearch-operator
      scope: public
      sourceNamespace: openshift-marketplace
# Custom Operand Configs: Watson Studio
# -----------------------------------------------------------------------------
---
apiVersion: operator.ibm.com/v1alpha1
kind: OperandConfig
metadata:
  name: opencontent-rabbitmq-registry
  namespace: "{{ cpd_operators_namespace }}"
spec:
  services:
    - name: rabbitmq-operator
      spec: {}
---
apiVersion: operator.ibm.com/v1alpha1
kind: OperandConfig
metadata:
  name: opencontent-elasticsearch-registry
  namespace: "{{ cpd_operators_namespace }}"
spec:
  services:
    - name: elasticsearch-operator
      spec: {}
