# Watson Studio 4.5 defines operand requests for ccs, datarefinery and ws-runtimes
# so these resources are created upfront to enable the subscriptions to start up
#
# Custom Operand Registries: Watson Studio
# -----------------------------------------------------------------------------
---
apiVersion: operator.ibm.com/v1alpha1
kind: OperandRegistry
metadata:
  name: ibm-cpd-ccs-registry
  namespace: ibm-cpd-operators
spec:
  operators:
    - channel: "{{ cpd_olm_utils_components.ccs.sub_channel }}"
      installPlanApproval: Automatic
      name: ibm-cpd-ccs-operator
      namespace: "{{ cpd_operators_namespace }}"
      packageName: ibm-cpd-ccs
      scope: public
      sourceNamespace: openshift-marketplace
      sourceName: ibm-operator-catalog
---
apiVersion: operator.ibm.com/v1alpha1
kind: OperandRegistry
metadata:
  name: ibm-cpd-datarefinery-registry
  namespace: ibm-cpd-operators
spec:
  operators:
    - channel: "{{ cpd_olm_utils_components.datarefinery.sub_channel }}"
      installPlanApproval: Automatic
      name: ibm-cpd-datarefinery-operator
      namespace: "{{ cpd_operators_namespace }}"
      packageName: ibm-cpd-datarefinery
      scope: public
      sourceNamespace: openshift-marketplace
---
apiVersion: operator.ibm.com/v1alpha1
kind: OperandRegistry
metadata:
  name: ibm-cpd-ws-runtimes-registry
  namespace: ibm-cpd-operators
spec:
  operators:
    - channel: "{{ cpd_olm_utils_components.ws_runtimes.sub_channel }}"
      installPlanApproval: Automatic
      name: ibm-cpd-ws-runtimes-operator
      namespace: "{{ cpd_operators_namespace }}"
      packageName: ibm-cpd-ws-runtimes
      scope: public
      sourceNamespace: openshift-marketplace
# Custom Operand Configs: Watson Studio
# -----------------------------------------------------------------------------
---
apiVersion: operator.ibm.com/v1alpha1
kind: OperandConfig
metadata:
  name: ibm-cpd-datarefinery-registry
  namespace: "{{ cpd_operators_namespace }}"
spec:
  services:
    - name: ibm-cpd-datarefinery-operator
      spec: {}
---
apiVersion: operator.ibm.com/v1alpha1
kind: OperandConfig
metadata:
  name: ibm-cpd-ws-runtimes-registry
  namespace: "{{ cpd_operators_namespace }}"
spec:
  services:
    - name: ibm-cpd-ws-runtimes-operator
      spec: {}
---
apiVersion: operator.ibm.com/v1alpha1
kind: OperandConfig
metadata:
  name: ibm-cpd-ccs-registry
  namespace: "{{ cpd_operators_namespace }}"
spec:
  services:
    - name: ibm-cpd-ccs-operator
      spec: {}
