apiVersion: v1
data:
  envoy-config-urlparam-private.json: "{\n  \"listeners\": [\n    {\n      \"address\":
    \"tcp://0.0.0.0:17600\",\n      \"ssl_context\": {\n        \"ca_cert_file\":
    \"/etc/private_certs/envoycacert.pem\",\n        \"cert_chain_file\": \"/etc/private_certs/cacertchain.pem\",\n
    \       \"private_key_file\": \"/etc/private_certs/key.pem\",\n        \"alpn_protocols\":
    \"h2,http/1.1\",\n        \"alt_alpn_protocols\": \"http/1.1\"\n      },\n      \"filters\":
    [\n        {\n          \"type\": \"read\",\n          \"name\": \"http_connection_manager\",\n
    \         \"config\": {\n            \"access_log\": [\n              {\n                \"format\":
    \"[%START_TIME%]  \\\"%REQ(X-FORWARDED-FOR)%\\\" - \\\"%REQ(USER-AGENT)%\\\"  \\\"%REQ(:METHOD)%
    %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\\\" %RESPONSE_CODE% %BYTES_RECEIVED%
    %BYTES_SENT%  x-request-id = \\\"%REQ(X-REQUEST-ID)%\\\" x-global-transaction-id
    = \\\"%REQ(X-GLOBAL-TRANSACTION-ID)%\\\" \\\"%REQ(:AUTHORITY)%\\\" \\\"%UPSTREAM_HOST%\\\"
    \\\"%UPSTREAM_CLUSTER%\\\"    rt=\\\"%DURATION%\\\" uct=\\\"%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%\\\"
    \\n\",\n                \"path\": \"/dev/stdout\"\n              }],\n            \"generate_request_id\":
    true,\n            \"codec_type\": \"auto\",\n            \"idle_timeout_s\":
    120,\n            \"stat_prefix\": \"ingress_http\",\n            \"route_config\":
    {\n              \"virtual_hosts\": [\n                {\n                  \"name\":
    \"service\",\n                  \"domains\": [\"*\"],\n                  \"require_ssl\":
    \"all\",\n                  \"routes\": [\n                    {\n                      \"timeout_ms\":
    600000,\n                      \"retry_policy\": {\n                          \"retry_on\":
    \"gateway-error,connect-failure\",\n                          \"num_retries\":
    120\n                          },\n     \t\t          \"prefix\": \"/\",\n     \t\t
    \         \"cluster_header\" : \"v4-deployment-id\"\n                    }\n                  ]\n
    \               }\n              ]\n            },\n            \"filters\": [\n
    \             {\n                \"type\": \"decoder\",\n                \"name\":
    \"router\",\n                \"config\": {}\n              }\n            ]\n
    \         }\n        }\n      ]\n    }\n  ],\n  \"admin\": {\n    \"access_log_path\":
    \"/dev/stdout\",\n    \"address\": \"tcp://0.0.0.0:8001\"\n  },\n  \"cluster_manager\":
    {\n    \"clusters\": [\n    ],\n    \"sds\": {\n      \"cluster\": {\n        \"name\":
    \"sds\",\n        \"connect_timeout_ms\": 120000,\n        \"type\": \"strict_dns\",\n
    \       \"lb_type\": \"round_robin\",\n        \"hosts\": [\n          {\n            \"url\":
    \"tcp://localhost:8081\"\n          }\n        ]\n      },\n      \"refresh_delay_ms\":
    1000\n    },\n    \"cds\": {\n      \"cluster\": {\n        \"name\": \"cds\",\n
    \       \"connect_timeout_ms\": 120000,\n        \"type\": \"strict_dns\",\n        \"lb_type\":
    \"round_robin\",\n        \"hosts\": [\n          {\n            \"url\": \"tcp://localhost:8081\"\n
    \         }\n        ]\n      },\n      \"refresh_delay_ms\": 100\n    },\n    \"outlier_detection\":
    {\n      \"event_log_path\": \"/dev/stdout\"\n    }\n  }\n}\n"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","data":{"envoy-config-urlparam-private.json":"{\n  \"listeners\":
      [\n    {\n      \"address\": \"tcp://0.0.0.0:17600\",\n      \"ssl_context\":
      {\n        \"ca_cert_file\": \"/etc/private_certs/envoycacert.pem\",\n        \"cert_chain_file\":
      \"/etc/private_certs/cacertchain.pem\",\n        \"private_key_file\": \"/etc/private_certs/key.pem\",\n        \"alpn_protocols\":
      \"h2,http/1.1\",\n        \"alt_alpn_protocols\": \"http/1.1\"\n      },\n      \"filters\":
      [\n        {\n          \"type\": \"read\",\n          \"name\": \"http_connection_manager\",\n          \"config\":
      {\n            \"access_log\": [\n              {\n                \"format\":
      \"[%START_TIME%]  \\\"%REQ(X-FORWARDED-FOR)%\\\" - \\\"%REQ(USER-AGENT)%\\\"  \\\"%REQ(:METHOD)%
      %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\\\" %RESPONSE_CODE% %BYTES_RECEIVED%
      %BYTES_SENT%  x-request-id = \\\"%REQ(X-REQUEST-ID)%\\\" x-global-transaction-id
      = \\\"%REQ(X-GLOBAL-TRANSACTION-ID)%\\\" \\\"%REQ(:AUTHORITY)%\\\" \\\"%UPSTREAM_HOST%\\\"
      \\\"%UPSTREAM_CLUSTER%\\\"    rt=\\\"%DURATION%\\\" uct=\\\"%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%\\\"
      \\n\",\n                \"path\": \"/dev/stdout\"\n              }],\n            \"generate_request_id\":
      true,\n            \"codec_type\": \"auto\",\n            \"idle_timeout_s\":
      120,\n            \"stat_prefix\": \"ingress_http\",\n            \"route_config\":
      {\n              \"virtual_hosts\": [\n                {\n                  \"name\":
      \"service\",\n                  \"domains\": [\"*\"],\n                  \"require_ssl\":
      \"all\",\n                  \"routes\": [\n                    {\n                      \"timeout_ms\":
      120000,\n                      \"retry_policy\": {\n                          \"retry_on\":
      \"gateway-error,connect-failure\",\n                          \"num_retries\":
      120\n                          },\n     \t\t          \"prefix\": \"/\",\n     \t\t          \"cluster_header\"
      : \"v4-deployment-id\"\n                    }\n                  ]\n                }\n              ]\n            },\n            \"filters\":
      [\n              {\n                \"type\": \"decoder\",\n                \"name\":
      \"router\",\n                \"config\": {}\n              }\n            ]\n          }\n        }\n      ]\n    }\n  ],\n  \"admin\":
      {\n    \"access_log_path\": \"/dev/stdout\",\n    \"address\": \"tcp://0.0.0.0:8001\"\n  },\n  \"cluster_manager\":
      {\n    \"clusters\": [\n    ],\n    \"sds\": {\n      \"cluster\": {\n        \"name\":
      \"sds\",\n        \"connect_timeout_ms\": 120000,\n        \"type\": \"strict_dns\",\n        \"lb_type\":
      \"round_robin\",\n        \"hosts\": [\n          {\n            \"url\": \"tcp://localhost:8081\"\n          }\n        ]\n      },\n      \"refresh_delay_ms\":
      1000\n    },\n    \"cds\": {\n      \"cluster\": {\n        \"name\": \"cds\",\n        \"connect_timeout_ms\":
      120000,\n        \"type\": \"strict_dns\",\n        \"lb_type\": \"round_robin\",\n        \"hosts\":
      [\n          {\n            \"url\": \"tcp://localhost:8081\"\n          }\n        ]\n      },\n      \"refresh_delay_ms\":
      100\n    },\n    \"outlier_detection\": {\n      \"event_log_path\": \"/dev/stdout\"\n    }\n  }\n}\n"},"kind":"ConfigMap","metadata":{"labels":{"app":"wml-deployment-envoy","app.kubernetes.io/instance":"ibm-wml-cpd","app.kubernetes.io/managed-by":"ansible","app.kubernetes.io/name":"ibm-wml-cpd"},"name":"wmlenvoyconfig","namespace":"ibm-cpd","ownerReferences":[{"apiVersion":"wml.cpd.ibm.com/v1beta1","kind":"WmlBase","name":"wml-cr","uid":"9180835e-660a-4106-9f22-7cf8b6738bbf"}]}}'
  creationTimestamp: "2022-09-18T19:15:04Z"
  labels:
    app: wml-deployment-envoy
    app.kubernetes.io/instance: ibm-wml-cpd
    app.kubernetes.io/managed-by: ansible
    app.kubernetes.io/name: ibm-wml-cpd
  name: wmlenvoyconfig
  namespace: ibm-cpd
  ownerReferences:
  - apiVersion: wml.cpd.ibm.com/v1beta1
    kind: WmlBase
    name: wml-cr
    uid: 9180835e-660a-4106-9f22-7cf8b6738bbf
  resourceVersion: "28562184"
  uid: 897e867b-bcbf-49e5-9402-a9c34258e12e
