---
# 1. Create CloudPak for Data CR
# -----------------------------------------------------------------------------
# https://www.ibm.com/docs/en/cloud-paks/cp-data/4.0?topic=installing-cloud-pak-data

- name: "install-cp4d : Install CloudPak for Data"
  kubernetes.core.k8s:
    apply: yes
    template: 'templates/ibmcpd.yml.j2'

# 2. Patch ZenService lite-cr to set the zen version and increase resource limits
# ----------------------------------------------------------------------------------------------
# 2.1 Wait for Zen operator ...
- name: "install-cp4d : Wait for ibm-zen-operator to be ready (60s delay)"
  kubernetes.core.k8s_info:
    api_version: apps/v1
    name: ibm-zen-operator
    namespace: ibm-common-services
    kind: Deployment
  register: zen_operator_lookup
  until: zen_operator_lookup.resources[0].status.availableReplicas is defined
  retries: 20 # Approximately 20 minutes before we give up
  delay: 60 # 1 minute

# 2.2 Wait for lite-cr to be created ...
- name: "install-cp4d : Wait for ZenService lite-cr to be created"
  kubernetes.core.k8s_info:
    api_version: zen.cpd.ibm.com/v1
    name: lite-cr
    namespace: "{{ cpd_instance_namespace }}"
    kind: ZenService
  register: zenlitecr_output
  until:
    - zenlitecr_output.resources is defined
    - zenlitecr_output.resources | length > 0
  retries: 60 # approx 30 minutes before we give up
  delay: 30 # seconds

# 2.3 Apply the patch per recommendation from CP4D team
- name: "install-cp4d : Patch ZenService lite-cr to set the zen version and increase resource limits"
  kubernetes.core.k8s:
    api_version: zen.cpd.ibm.com/v1
    name: lite-cr
    namespace: "{{ cpd_instance_namespace }}"
    kind: ZenService
    definition:
      spec:
        version: "{{ zen_cr_version }}"
        scaleConfig: medium
        ZenCoreMetaDb:
          name: zen-metastoredb
          kind: StatefulSet
          container: zen-metastoredb
          replicas: 3
          resources:
            limits:
              cpu: 2
              memory: 4Gi
            requests:
              cpu: 200m
              memory: 1024Mi
    apply: true

# 2.4 Delete zen-operator pod to force the reconcile from the beginning after lite-cr is patched.
# This is just a bit of a hacky way to force zen operator to read the zen version we specify.
# Otherwise it will always installed the latest supported zen version available in zen operator.
# Accordingly to CPD docs: "The Zen operator provides the Cloud Pak for Data control plane.
# "The version of Zen is determined by the version of IBM Cloud Pak foundational services that you install on your cluster.
# If you install the minimum required version of IBM Cloud Pak foundational services, the Zen version should correspond to the version in the table.
# If you install a later version of IBM Cloud Pak foundational services, you might see a later version of Zen."
# Reference: https://www.ibm.com/docs/en/cloud-paks/cp-data/4.5.x?topic=planning-operator-operand-versions
- name: "install-cp4d : Scale down ibm-zen-operator"
  kubernetes.core.k8s:
    api_version: apps/v1
    name: ibm-zen-operator
    namespace: ibm-common-services
    kind: Deployment
    definition:
      spec:
        replicas: 0
    apply: true

- name: "install-cp4d : Scale up ibm-zen-operator to force reconcile"
  kubernetes.core.k8s:
    api_version: apps/v1
    name: ibm-zen-operator
    namespace: ibm-common-services
    kind: Deployment
    definition:
      spec:
        replicas: 1
    apply: true

# 2.5 Wait for Zen operator ...
- name: "install-cp4d : Wait for ibm-zen-operator to be ready again (60s delay)"
  kubernetes.core.k8s_info:
    api_version: apps/v1
    name: ibm-zen-operator
    namespace: ibm-common-services
    kind: Deployment
  register: zen_operator_lookup
  until: zen_operator_lookup.resources[0].status.availableReplicas is defined
  retries: 20 # Approximately 20 minutes before we give up
  delay: 60 # 1 minute

# 3. Wait for controlPlaneStatus
# -----------------------------------------------------------------------------
# oc get Ibmcpd ibmcpd-cr -o jsonpath="{.status.controlPlaneStatus}{'\n'}"
- name: "install-cp4d : Wait for controlPlaneStatus to be 'Completed' (2m delay)"
  kubernetes.core.k8s_info:
    api_version: cpd.ibm.com/v1
    name: ibmcpd
    namespace: "{{ cpd_instance_namespace }}"
    kind: Ibmcpd
  register: ibmcpd_lookup
  until:
    - ibmcpd_lookup.resources[0].status.controlPlaneStatus is defined
    - ibmcpd_lookup.resources[0].status.controlPlaneStatus == "Completed"
  retries: 60 # Approximately 2 hours before we give up
  delay: 120 # 2 minutes


# 4. Wait for zenStatus
# -----------------------------------------------------------------------------
# oc get ZenService lite-cr -o jsonpath="{.status.zenStatus}{'\n'}"
- name: "install-cp4d : Wait for zenStatus to be ready to be 'Completed' (2m delay)"
  kubernetes.core.k8s_info:
    api_version: zen.cpd.ibm.com/v1
    name: lite-cr
    namespace: "{{ cpd_instance_namespace }}"
    kind: ZenService
  register: zenservice_lookup
  until:
    - zenservice_lookup.resources[0].status.zenStatus is defined
    - zenservice_lookup.resources[0].status.zenStatus == "Completed" or zenservice_lookup.resources[0].status.zenStatus == "Failed"
  retries: 60 # Approximately 2 hours before we give up
  delay: 120 # 5 minutes

- name: "install-cp4d : Check that the zenStatus is 'Completed'"
  assert:
    that: zenservice_lookup.resources[0].status.zenStatus == "Completed"
    fail_msg: "IBM CloudPak for Data install failed (zenStatus)"


# 5. Provide CP4D dashboard URL
# -----------------------------------------------------------------------------
- name: "install-cp4d : Obtain CP4D dashboard URL"
  debug:
    msg:
      - "CP4D Dashboard ......................... https://{{zenservice_lookup.resources[0].status.url}}"
      - "CP4D Username .......................... admin"
      - "CP4D Password .......................... Found in 'admin-user-details' secret under '{{ cpd_instance_namespace }}' namespace"
