---
# 1. Debug
# -----------------------------------------------------------------------------
- name: "Check that CPD Service name and product version has been provided"
  assert:
    that:
      - cpd_service_name is defined and cpd_service_name != ""
      - cpd_product_version is defined and cpd_product_version != ""
    fail_msg: "CPD service name (cpd_service_name) and version (cpd_product_version) are required parameter to run this role"

- name: "Check that provided CPD product version is supported"
  assert:
    that:
      - cpd_product_version in cpd_supported_versions # Ensure only CPD 4.0.x and 4.5.x are supported
    fail_msg: "CPD product version ({{ cpd_product_version }}) is not a supported CPD product/service version. Supported CPD product versions are: {{ cpd_supported_versions }}."

# 2. Run the installation
# -----------------------------------------------------------------------------
- name: "Run install"
  include_tasks: "install.yml"
